/*
 * Swagger Petstore
 *
 * This is a sample Petstore server.  You can find out more about Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).
 *
 * API version: 1.0.0
 * Contact: apiteam@swagger.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package main

import (
	"log"
	"net/http"

	"github.com/mytest/api/internal/rclient"
	"github.com/mytest/api/internal/workerpool"
	"github.com/mytest/api/swagger"
)

func main() {
	log.Printf("Server started")

	// os.Setenv("REDIS_SERVER_URL", "localhost:55000")
	// os.Setenv("REDIS_SERVER_PWD", "redispw")

	//router := sw.NewRouter()
	router := swagger.NewRouter()

	rdsClient, err := rclient.GetRedisClient()
	if err != nil {
		panic(err)
	}
	workerpool := workerpool.GetRedisWorkerPool(rdsClient)
	workerpool.StartWorkers()

	log.Fatal(http.ListenAndServe(":8080", router))
}
